### PR TITLE
DEV: add new sprockets directive to require discourse folders

### PR DESCRIPTION
**Pull request by fzngagan**

### CODE REVIEW

**Review by angusmcleod — COMMENTED** [review]
@fzngagan Let's get the plugin guard to support this before we merge. We need to be able to deploy to Try.

**Comment by angusmcleod** [comment]
@fzngagan What's the status on this one?

**Comment by fzngagan** [comment]
@angusmcleod 
Let's discuss this on our call tomorrow and get it merged. With my last experiment, CW started to work but then the Landing Pages plugin was caught by the plugin guard as a false positive.

**Comment by fzngagan** [comment]
@angusmcleod 
I've made some changes to the plugin guard and its working now. I think we can merge now.

**Pull request merged**
