### PR TITLE
DEV: Pin plugin for Discourse 3.1 stable

### PR DESCRIPTION
**Pull request by jumagura**

### CODE REVIEW

**Review by o7n — APPROVED** [review]
Tested on stable and rolls back to the correct commit 👍

**Review by merefield — APPROVED** [review]

**Comment by merefield** [comment]
@jumagura sorry, there's been an intervening release, please can update the version! :)

**Review by merefield — CHANGES_REQUESTED** [review]
Version update

**Review by merefield — APPROVED** [review]
I've fixed the conflict.  Thanks!

**Pull request merged**
