### PR TITLE
FEATURE: add can_create_tag

### PR DESCRIPTION
**Pull request by angusmcleod**
@merefield Perhaps @jumagura can review this one? What do you think.

### CODE REVIEW

**Comment by angusmcleod** [comment]
@merefield Just bumping this one back up. Thoughts?

> @merefield Perhaps @jumagura can review this one? What do you think.

**Comment by jumagura** [comment]
Hi @angusmcleod. Everything seems great 🌟  Just one question: Should changes made in  `lefthook.yml` be part of this feature PR? Sorry for my lack of knowledge. 

Besides that this PR can be merged. 😃

**Review by jumagura — COMMENTED** [review]
Hi @angusmcleod. Everything seems great 🌟 Just one question: Should changes made in `lefthook.yml` be part of this feature PR? I'm asking because my lack of knowledge. I apologize for that.

Besides that doubt, this PR can be merged. 😃

**Comment by angusmcleod** [comment]
@jumagura Yes a good question about lefthook. The reason they were necessary is because lefthook was preventing the change to the locale file in this PR as we don't quite follow the `discourse/discourse` i18n lefthook formatting where that check was originally imported from. A separate PR will be needed to bring both this plugin and lefthook in full conformity with `discourse/discourse` i18n linting.

**Comment by angusmcleod** [comment]
@jumagura Once the reviewer is happy with the PR, they can merge it. Note that there is a version conflict with `main` which is bound to happen every now and then as some PR's take longer than others and the version is bumped in each PR.

**Pull request merged**
