### PR TITLE
Admin acceptance tests

### PR DESCRIPTION
**Pull request by jumagura**

### CODE REVIEW

**Comment by jumagura** [comment]
@angusmcleod I managed to make it pass all checks. I skipped two acceptance tests, since I have to fix those bugs triggered in `admin-submissions-test` and `admin-logs-test`

**Comment by angusmcleod** [comment]
@jumagura Nice work! These are looking great.

There's a few things we still need to cover here.

1. The API Admin panel.
2. Adding, editing and removing custom fields. You've covered the listing of fields, but we need to cover field CRUD too.
3. Editing submission columns (including the modal). Likewise, you've covered the listing of submissions. We need to cover the interactive controls too.
4. The import, export and destroy processes in the Manage panel. Likewise, you've covered the listing elements. We need to cover the interactive elements too.
5. These UI elements in the wizard panel:
  - Image inputs (e.g. step banners and field images)
  - Text editors (e.g. step and field descriptions)
  - The wizard mapper component and it's different configurations, in particular "Set" (aka "Assignment") and "If" (aka "Conditional"). Those two configurations are used a lot and need some decent test coverage.

**Comment by angusmcleod** [comment]
@jumagura Is this ready for another review?

**Comment by jumagura** [comment]
Hi @angusmcleod i'm still working on it. Qunit tests that were functional before need to be updated. I'm doing that now.

**Comment by angusmcleod** [comment]
@merefield @jumagura Let's get this merged soon :)

**Comment by angusmcleod** [comment]
@jumagura @merefield What's the status on this one guys? Would love to get it merged.

**Comment by jumagura** [comment]
Hi @angusmcleod 
This has been done so far:

- [x] The API Admin panel.
- [x] Adding, editing and removing custom fields. You've covered the listing of fields, but we need to cover field CRUD too.
- [x] Editing submission columns (including the modal). Likewise, you've covered the listing of submissions. We need to cover the interactive controls too.
- [x] The import, export and destroy processes in the Manage panel. Likewise, you've covered the listing elements. We need to cover the interactive elements too.

What needs to be finished is the UI elements in the wizard panel:

- [ ] Image inputs (e.g. step banners and field images)
- [ ] Text editors (e.g. step and field descriptions)
- [ ] The wizard mapper component and it's different configurations, in particular "Set" (aka "Assignment") and "If" (aka "Conditional"). Those two configurations are used a lot and need some decent test coverage.

**Comment by angusmcleod** [comment]
Ok 👍 let @merefield know how you're going on your next meeting.

**Comment by jumagura** [comment]
Hi @merefield I finished the admin-panel acceptance tests:
These last requirements from Angus are done.
- [X]  The API Admin panel.
- [X]  Adding, editing and removing custom fields. You've covered the listing of fields, but we need to cover field CRUD too.
- [X]  Editing submission columns (including the modal). Likewise, you've covered the listing of submissions. We need to cover the interactive controls too.
- [X]  The import, export and destroy processes in the Manage panel. Likewise, you've covered the listing elements. We need to cover the interactive elements too.
- [X]  Text editors (e.g. step and field descriptions)
- [X]  The wizard mapper component and it's different configurations, in particular "Set" (aka "Assignment") and "If" (aka "Conditional"). Those two configurations are used a lot and need some decent test coverage.

I have completed all the acceptance tests according to the specifications, covering the main functionalities and workflows of the admin panel.

About images upload feature testing - an acceptance test isn't the best fit here due to some limitations with file uploads. A component test should work great and I'll start working on it early next week and will keep you posted. As always, appreciate your patience and understanding!

The backend check failed since I merged main before pushing this branch.

Have a great day!

**Comment by merefield** [comment]
@jumagura what's the problem with the back-end test here?

**Comment by jumagura** [comment]
Hi @merefield. It is solved. It was related to the main branch. Angus fixed that failing test and now I'm merging main again.

**Comment by merefield** [comment]
That's weird, I run this locally and I'm getting 6 failing tests, any thoughts?:

```
<ol id="qunit-tests" style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none;"><li id="qunit-test-output-64fda1bc" class="fail"><strong><span class="module-name">Acceptance: Admin | Custom Fields Unsuscribed</span>:<span class="Apple-converted-space"> </span><span class="test-name">view available custom fields for unsubscribed plan</span><span class="Apple-converted-space"> </span><b class="counts">(<b class="failed">1</b>,<span class="Apple-converted-space"> </span><b class="passed">5</b>, 6)</b></strong><a href="http://localhost:4200/tests?qunit_single_plugin=discourse-custom-wizard&amp;qunit_skip_core=1&amp;hidepassed&amp;testId=64fda1bc">Rerun</a><span class="runtime">367 ms</span><ol class="qunit-assert-list"><li class="pass"><span class="test-message">custom field class is present</span><span class="runtime">@ 329 ms</span></li><li class="pass"><span class="test-message">custom field type is present</span><span class="runtime">@ 330 ms</span></li><li class="pass"><span class="test-message">custom field name is present</span><span class="runtime">@ 330 ms</span></li><li class="pass"><span class="test-message">custom field serializer is present</span><span class="runtime">@ 330 ms</span></li><li class="pass"><span class="test-message">custom field action buttons are present</span><span class="runtime">@ 330 ms</span></li><li class="fail"><span class="test-message">Promise rejected during "view available custom fields for unsubscribed plan": Element.querySelector: '.admin-wizard-container details:has(summary[name="Filter by: Select a class"])' is not a valid selector</span><span class="runtime">@ 330 ms</span>

Source: | query@http://localhost:4200/assets/test-helpers.js:29350:53 checkSelectKitIsNotExpanded@http://localhost:4200/assets/test-helpers.js:29763:33 expandSelectKit@http://localhost:4200/assets/test-helpers.js:29775:32 expand@http://localhost:4200/assets/test-helpers.js:29917:15 @http://localhost:4200/assets/plugins/test/discourse-custom-wizard_tests.js:71:23
-- | --


</li></ol><p class="qunit-source"><strong>Source:<span class="Apple-converted-space"> </span></strong>@http://localhost:4200/assets/plugins/test/discourse-custom-wizard_tests.js:62:21 acceptance/&lt;@http://localhost:4200/assets/test-helpers.js:29276:17 processModule@http://localhost:4200/assets/chunk.vendors-node_modules_pretender_dist_pretender_es_js-node_modules_qunit_qunit_qunit_js-node_mo-a05e2f.dac4c13058b8c0d88081.js:3856:622 module$1@http://localhost:4200/assets/chunk.vendors-node_modules_pretender_dist_pretender_es_js-node_modules_qunit_qunit_qunit_js-node_mo-a05e2f.dac4c13058b8c0d88081.js:3861:105 acceptance@http://localhost:4200/assets/test-helpers.js:29272:25 @http://localhost:4200/assets/plugins/test/discourse-custom-wizard_tests.js:5:32 Module.prototype.exports@http://localhost:4200/assets/vendor.js:11007:32 requireModule@http://localhost:4200/assets/vendor.js:10928:18 require@http://localhost:4200/assets/test-support.js:31593:16 loadModules/&lt;@http://localhost:4200/assets/test-support.js:31936:17 loadModules@http://localhost:4200/assets/test-support.js:31935:27 @http://localhost:4200/assets/test-helpers.js:31034:12 @http://localhost:4200/assets/scripts/discourse-boot.js:20:12 @http://localhost:4200/assets/scripts/discourse-boot.js:21:3</p></li><li id="qunit-test-output-c08ea45e" class="fail"><strong><span class="module-name">Acceptance: Admin | Custom Fields Unsuscribed</span>:<span class="Apple-converted-space"> </span><span class="test-name">change custom fields for unsubscribed plan</span><span class="Apple-converted-space"> </span><b class="counts">(<b class="failed">1</b>,<span class="Apple-converted-space"> </span><b class="passed">0</b>, 1)</b></strong><a href="http://localhost:4200/tests?qunit_single_plugin=discourse-custom-wizard&amp;qunit_skip_core=1&amp;hidepassed&amp;testId=c08ea45e">Rerun</a><span class="runtime">238 ms</span><p class="qunit-source"><strong>Source:<span class="Apple-converted-space"> </span></strong>@http://localhost:4200/assets/plugins/test/discourse-custom-wizard_tests.js:83:21 acceptance/&lt;@http://localhost:4200/assets/test-helpers.js:29276:17 processModule@http://localhost:4200/assets/chunk.vendors-node_modules_pretender_dist_pretender_es_js-node_modules_qunit_qunit_qunit_js-node_mo-a05e2f.dac4c13058b8c0d88081.js:3856:622 module$1@http://localhost:4200/assets/chunk.vendors-node_modules_pretender_dist_pretender_es_js-node_modules_qunit_qunit_qunit_js-node_mo-a05e2f.dac4c13058b8c0d88081.js:3861:105 acceptance@http://localhost:4200/assets/test-helpers.js:29272:25 @http://localhost:4200/assets/plugins/test/discourse-custom-wizard_tests.js:5:32 Module.prototype.exports@http://localhost:4200/assets/vendor.js:11007:32 requireModule@http://localhost:4200/assets/vendor.js:10928:18 require@http://localhost:4200/assets/test-support.js:31593:16 loadModules/&lt;@http://localhost:4200/assets/test-support.js:31936:17 loadModules@http://localhost:4200/assets/test-support.js:31935:27 @http://localhost:4200/assets/test-helpers.js:31034:12 @http://localhost:4200/assets/scripts/discourse-boot.js:20:12 @http://localhost:4200/assets/scripts/discourse-boot.js:21:3</p></li><li id="qunit-test-output-58a9e79f" class="fail"><strong><span class="module-name">Acceptance: Admin | Custom Fields Unsuscribed</span>:<span class="Apple-converted-space"> </span><span class="test-name">Create Topic and Post custom fields</span><span class="Apple-converted-space"> </span><b class="counts">(<b class="failed">1</b>,<span class="Apple-converted-space"> </span><b class="passed">1</b>, 2)</b></strong><a href="http://localhost:4200/tests?qunit_single_plugin=discourse-custom-wizard&amp;qunit_skip_core=1&amp;hidepassed&amp;testId=58a9e79f">Rerun</a><span class="runtime">198 ms</span><p class="qunit-source"><strong>Source:<span class="Apple-converted-space"> </span></strong>@http://localhost:4200/assets/plugins/test/discourse-custom-wizard_tests.js:101:21 acceptance/&lt;@http://localhost:4200/assets/test-helpers.js:29276:17 processModule@http://localhost:4200/assets/chunk.vendors-node_modules_pretender_dist_pretender_es_js-node_modules_qunit_qunit_qunit_js-node_mo-a05e2f.dac4c13058b8c0d88081.js:3856:622 module$1@http://localhost:4200/assets/chunk.vendors-node_modules_pretender_dist_pretender_es_js-node_modules_qunit_qunit_qunit_js-node_mo-a05e2f.dac4c13058b8c0d88081.js:3861:105 acceptance@http://localhost:4200/assets/test-helpers.js:29272:25 @http://localhost:4200/assets/plugins/test/discourse-custom-wizard_tests.js:5:32 Module.prototype.exports@http://localhost:4200/assets/vendor.js:11007:32 requireModule@http://localhost:4200/assets/vendor.js:10928:18 require@http://localhost:4200/assets/test-support.js:31593:16 loadModules/&lt;@http://localhost:4200/assets/test-support.js:31936:17 loadModules@http://localhost:4200/assets/test-support.js:31935:27 @http://localhost:4200/assets/test-helpers.js:31034:12 @http://localhost:4200/assets/scripts/discourse-boot.js:20:12 @http://localhost:4200/assets/scripts/discourse-boot.js:21:3</p></li><li id="qunit-test-output-6608a7ec" class="fail"><strong><span class="module-name">Acceptance: Admin | Custom Fields Unsuscribed</span>:<span class="Apple-converted-space"> </span><span class="test-name">Update Topic custom field</span><span class="Apple-converted-space"> </span><b class="counts">(<b class="failed">1</b>,<span class="Apple-converted-space"> </span><b class="passed">0</b>, 1)</b></strong><a href="http://localhost:4200/tests?qunit_single_plugin=discourse-custom-wizard&amp;qunit_skip_core=1&amp;hidepassed&amp;testId=6608a7ec">Rerun</a><span class="runtime">174 ms</span><p class="qunit-source"><strong>Source:<span class="Apple-converted-space"> </span></strong>@http://localhost:4200/assets/plugins/test/discourse-custom-wizard_tests.js:126:21 acceptance/&lt;@http://localhost:4200/assets/test-helpers.js:29276:17 processModule@http://localhost:4200/assets/chunk.vendors-node_modules_pretender_dist_pretender_es_js-node_modules_qunit_qunit_qunit_js-node_mo-a05e2f.dac4c13058b8c0d88081.js:3856:622 module$1@http://localhost:4200/assets/chunk.vendors-node_modules_pretender_dist_pretender_es_js-node_modules_qunit_qunit_qunit_js-node_mo-a05e2f.dac4c13058b8c0d88081.js:3861:105 acceptance@http://localhost:4200/assets/test-helpers.js:29272:25 @http://localhost:4200/assets/plugins/test/discourse-custom-wizard_tests.js:5:32 Module.prototype.exports@http://localhost:4200/assets/vendor.js:11007:32 requireModule@http://localhost:4200/assets/vendor.js:10928:18 require@http://localhost:4200/assets/test-support.js:31593:16 loadModules/&lt;@http://localhost:4200/assets/test-support.js:31936:17 loadModules@http://localhost:4200/assets/test-support.js:31935:27 @http://localhost:4200/assets/test-helpers.js:31034:12 @http://localhost:4200/assets/scripts/discourse-boot.js:20:12 @http://localhost:4200/assets/scripts/discourse-boot.js:21:3</p></li><li id="qunit-test-output-36661bca" class="fail"><strong><span class="module-name">Acceptance: Admin | Custom Fields Unsuscribed</span>:<span class="Apple-converted-space"> </span><span class="test-name">Delete Topic custom field</span><span class="Apple-converted-space"> </span><b class="counts">(<b class="failed">1</b>,<span class="Apple-converted-space"> </span><b class="passed">1</b>, 2)</b></strong><a href="http://localhost:4200/tests?qunit_single_plugin=discourse-custom-wizard&amp;qunit_skip_core=1&amp;hidepassed&amp;testId=36661bca">Rerun</a><span class="runtime">205 ms</span><p class="qunit-source"><strong>Source:<span class="Apple-converted-space"> </span></strong>@http://localhost:4200/assets/plugins/test/discourse-custom-wizard_tests.js:145:21 acceptance/&lt;@http://localhost:4200/assets/test-helpers.js:29276:17 processModule@http://localhost:4200/assets/chunk.vendors-node_modules_pretender_dist_pretender_es_js-node_modules_qunit_qunit_qunit_js-node_mo-a05e2f.dac4c13058b8c0d88081.js:3856:622 module$1@http://localhost:4200/assets/chunk.vendors-node_modules_pretender_dist_pretender_es_js-node_modules_qunit_qunit_qunit_js-node_mo-a05e2f.dac4c13058b8c0d88081.js:3861:105 acceptance@http://localhost:4200/assets/test-helpers.js:29272:25 @http://localhost:4200/assets/plugins/test/discourse-custom-wizard_tests.js:5:32 Module.prototype.exports@http://localhost:4200/assets/vendor.js:11007:32 requireModule@http://localhost:4200/assets/vendor.js:10928:18 require@http://localhost:4200/assets/test-support.js:31593:16 loadModules/&lt;@http://localhost:4200/assets/test-support.js:31936:17 loadModules@http://localhost:4200/assets/test-support.js:31935:27 @http://localhost:4200/assets/test-helpers.js:31034:12 @http://localhost:4200/assets/scripts/discourse-boot.js:20:12 @http://localhost:4200/assets/scripts/discourse-boot.js:21:3</p></li><li id="qunit-test-output-0d843e79" class="fail"><strong><span class="module-name">Acceptance: Admin | API tab</span>:<span class="Apple-converted-space"> </span><span class="test-name">Visit API tab and fill data</span><span class="Apple-converted-space"> </span><b class="counts">(<b class="failed">1</b>,<span class="Apple-converted-space"> </span><b class="passed">3</b>, 4)</b></strong><a href="http://localhost:4200/tests?qunit_single_plugin=discourse-custom-wizard&amp;qunit_skip_core=1&amp;hidepassed&amp;testId=0d843e79">Rerun</a><span class="runtime">362 ms</span><p class="qunit-source"><strong>Source:<span class="Apple-converted-space"> </span></strong>@http://localhost:4200/assets/plugins/test/discourse-custom-wizard_tests.js:449:21 acceptance/&lt;@http://localhost:4200/assets/test-helpers.js:29276:17 processModule@http://localhost:4200/assets/chunk.vendors-node_modules_pretender_dist_pretender_es_js-node_modules_qunit_qunit_qunit_js-node_mo-a05e2f.dac4c13058b8c0d88081.js:3856:622 module$1@http://localhost:4200/assets/chunk.vendors-node_modules_pretender_dist_pretender_es_js-node_modules_qunit_qunit_qunit_js-node_mo-a05e2f.dac4c13058b8c0d88081.js:3861:105 acceptance@http://localhost:4200/assets/test-helpers.js:29272:25 @http://localhost:4200/assets/plugins/test/discourse-custom-wizard_tests.js:408:32 Module.prototype.exports@http://localhost:4200/assets/vendor.js:11007:32 requireModule@http://localhost:4200/assets/vendor.js:10928:18 require@http://localhost:4200/assets/test-support.js:31593:16 loadModules/&lt;@http://localhost:4200/assets/test-support.js:31936:17 loadModules@http://localhost:4200/assets/test-support.js:31935:27 @http://localhost:4200/assets/test-helpers.js:31034:12 @http://localhost:4200/assets/scripts/discourse-boot.js:20:12 @http://localhost:4200/assets/scripts/discourse-boot.js:21:3</p></li></ol>Acceptance: Admin | Custom Fields Unsuscribed: view available custom fields for unsubscribed plan (1, 5, 6)[Rerun](http://localhost:4200/tests?qunit_single_plugin=discourse-custom-wizard&qunit_skip_core=1&hidepassed&testId=64fda1bc)367 ms
        custom field class is present@ 329 ms
        custom field type is present@ 330 ms
        custom field name is present@ 330 ms
        custom field serializer is present@ 330 ms
        custom field action buttons are present@ 330 ms
        Promise rejected during "view available custom fields for unsubscribed plan": Element.querySelector: '.admin-wizard-container details:has(summary[name="Filter by: Select a class"])' is not a valid selector@ 330 ms
        Source: 	

        query@http://localhost:4200/assets/test-helpers.js:29350:53
        checkSelectKitIsNotExpanded@http://localhost:4200/assets/test-helpers.js:29763:33
        expandSelectKit@http://localhost:4200/assets/test-helpers.js:29775:32
        expand@http://localhost:4200/assets/test-helpers.js:29917:15
        @http://localhost:4200/assets/plugins/test/discourse-custom-wizard_tests.js:71:23

    Source: @http://localhost:4200/assets/plugins/test/discourse-custom-wizard_tests.js:62:21 acceptance/<@http://localhost:4200/assets/test-helpers.js:29276:17 processModule@http://localhost:4200/assets/chunk.vendors-node_modules_pretender_dist_pretender_es_js-node_modules_qunit_qunit_qunit_js-node_mo-a05e2f.dac4c13058b8c0d88081.js:3856:622 module$1@http://localhost:4200/assets/chunk.vendors-node_modules_pretender_dist_pretender_es_js-node_modules_qunit_qunit_qunit_js-node_mo-a05e2f.dac4c13058b8c0d88081.js:3861:105 acceptance@http://localhost:4200/assets/test-helpers.js:29272:25 @http://localhost:4200/assets/plugins/test/discourse-custom-wizard_tests.js:5:32 Module.prototype.exports@http://localhost:4200/assets/vendor.js:11007:32 requireModule@http://localhost:4200/assets/vendor.js:10928:18 require@http://localhost:4200/assets/test-support.js:31593:16 loadModules/<@http://localhost:4200/assets/test-support.js:31936:17 loadModules@http://localhost:4200/assets/test-support.js:31935:27 @http://localhost:4200/assets/test-helpers.js:31034:12 @http://localhost:4200/assets/scripts/discourse-boot.js:20:12 @http://localhost:4200/assets/scripts/discourse-boot.js:21:3
    Acceptance: Admin | Custom Fields Unsuscribed: change custom fields for unsubscribed plan (1, 0, 1)[Rerun](http://localhost:4200/tests?qunit_single_plugin=discourse-custom-wizard&qunit_skip_core=1&hidepassed&testId=c08ea45e)238 ms

    Source: @http://localhost:4200/assets/plugins/test/discourse-custom-wizard_tests.js:83:21 acceptance/<@http://localhost:4200/assets/test-helpers.js:29276:17 processModule@http://localhost:4200/assets/chunk.vendors-node_modules_pretender_dist_pretender_es_js-node_modules_qunit_qunit_qunit_js-node_mo-a05e2f.dac4c13058b8c0d88081.js:3856:622 module$1@http://localhost:4200/assets/chunk.vendors-node_modules_pretender_dist_pretender_es_js-node_modules_qunit_qunit_qunit_js-node_mo-a05e2f.dac4c13058b8c0d88081.js:3861:105 acceptance@http://localhost:4200/assets/test-helpers.js:29272:25 @http://localhost:4200/assets/plugins/test/discourse-custom-wizard_tests.js:5:32 Module.prototype.exports@http://localhost:4200/assets/vendor.js:11007:32 requireModule@http://localhost:4200/assets/vendor.js:10928:18 require@http://localhost:4200/assets/test-support.js:31593:16 loadModules/<@http://localhost:4200/assets/test-support.js:31936:17 loadModules@http://localhost:4200/assets/test-support.js:31935:27 @http://localhost:4200/assets/test-helpers.js:31034:12 @http://localhost:4200/assets/scripts/discourse-boot.js:20:12 @http://localhost:4200/assets/scripts/discourse-boot.js:21:3
    Acceptance: Admin | Custom Fields Unsuscribed: Create Topic and Post custom fields (1, 1, 2)[Rerun](http://localhost:4200/tests?qunit_single_plugin=discourse-custom-wizard&qunit_skip_core=1&hidepassed&testId=58a9e79f)198 ms

    Source: @http://localhost:4200/assets/plugins/test/discourse-custom-wizard_tests.js:101:21 acceptance/<@http://localhost:4200/assets/test-helpers.js:29276:17 processModule@http://localhost:4200/assets/chunk.vendors-node_modules_pretender_dist_pretender_es_js-node_modules_qunit_qunit_qunit_js-node_mo-a05e2f.dac4c13058b8c0d88081.js:3856:622 module$1@http://localhost:4200/assets/chunk.vendors-node_modules_pretender_dist_pretender_es_js-node_modules_qunit_qunit_qunit_js-node_mo-a05e2f.dac4c13058b8c0d88081.js:3861:105 acceptance@http://localhost:4200/assets/test-helpers.js:29272:25 @http://localhost:4200/assets/plugins/test/discourse-custom-wizard_tests.js:5:32 Module.prototype.exports@http://localhost:4200/assets/vendor.js:11007:32 requireModule@http://localhost:4200/assets/vendor.js:10928:18 require@http://localhost:4200/assets/test-support.js:31593:16 loadModules/<@http://localhost:4200/assets/test-support.js:31936:17 loadModules@http://localhost:4200/assets/test-support.js:31935:27 @http://localhost:4200/assets/test-helpers.js:31034:12 @http://localhost:4200/assets/scripts/discourse-boot.js:20:12 @http://localhost:4200/assets/scripts/discourse-boot.js:21:3
    Acceptance: Admin | Custom Fields Unsuscribed: Update Topic custom field (1, 0, 1)[Rerun](http://localhost:4200/tests?qunit_single_plugin=discourse-custom-wizard&qunit_skip_core=1&hidepassed&testId=6608a7ec)174 ms

    Source: @http://localhost:4200/assets/plugins/test/discourse-custom-wizard_tests.js:126:21 acceptance/<@http://localhost:4200/assets/test-helpers.js:29276:17 processModule@http://localhost:4200/assets/chunk.vendors-node_modules_pretender_dist_pretender_es_js-node_modules_qunit_qunit_qunit_js-node_mo-a05e2f.dac4c13058b8c0d88081.js:3856:622 module$1@http://localhost:4200/assets/chunk.vendors-node_modules_pretender_dist_pretender_es_js-node_modules_qunit_qunit_qunit_js-node_mo-a05e2f.dac4c13058b8c0d88081.js:3861:105 acceptance@http://localhost:4200/assets/test-helpers.js:29272:25 @http://localhost:4200/assets/plugins/test/discourse-custom-wizard_tests.js:5:32 Module.prototype.exports@http://localhost:4200/assets/vendor.js:11007:32 requireModule@http://localhost:4200/assets/vendor.js:10928:18 require@http://localhost:4200/assets/test-support.js:31593:16 loadModules/<@http://localhost:4200/assets/test-support.js:31936:17 loadModules@http://localhost:4200/assets/test-support.js:31935:27 @http://localhost:4200/assets/test-helpers.js:31034:12 @http://localhost:4200/assets/scripts/discourse-boot.js:20:12 @http://localhost:4200/assets/scripts/discourse-boot.js:21:3
    Acceptance: Admin | Custom Fields Unsuscribed: Delete Topic custom field (1, 1, 2)[Rerun](http://localhost:4200/tests?qunit_single_plugin=discourse-custom-wizard&qunit_skip_core=1&hidepassed&testId=36661bca)205 ms

    Source: @http://localhost:4200/assets/plugins/test/discourse-custom-wizard_tests.js:145:21 acceptance/<@http://localhost:4200/assets/test-helpers.js:29276:17 processModule@http://localhost:4200/assets/chunk.vendors-node_modules_pretender_dist_pretender_es_js-node_modules_qunit_qunit_qunit_js-node_mo-a05e2f.dac4c13058b8c0d88081.js:3856:622 module$1@http://localhost:4200/assets/chunk.vendors-node_modules_pretender_dist_pretender_es_js-node_modules_qunit_qunit_qunit_js-node_mo-a05e2f.dac4c13058b8c0d88081.js:3861:105 acceptance@http://localhost:4200/assets/test-helpers.js:29272:25 @http://localhost:4200/assets/plugins/test/discourse-custom-wizard_tests.js:5:32 Module.prototype.exports@http://localhost:4200/assets/vendor.js:11007:32 requireModule@http://localhost:4200/assets/vendor.js:10928:18 require@http://localhost:4200/assets/test-support.js:31593:16 loadModules/<@http://localhost:4200/assets/test-support.js:31936:17 loadModules@http://localhost:4200/assets/test-support.js:31935:27 @http://localhost:4200/assets/test-helpers.js:31034:12 @http://localhost:4200/assets/scripts/discourse-boot.js:20:12 @http://localhost:4200/assets/scripts/discourse-boot.js:21:3
    Acceptance: Admin | API tab: Visit API tab and fill data (1, 3, 4)[Rerun](http://localhost:4200/tests?qunit_single_plugin=discourse-custom-wizard&qunit_skip_core=1&hidepassed&testId=0d843e79)362 ms

    Source: @http://localhost:4200/assets/plugins/test/discourse-custom-wizard_tests.js:449:21 acceptance/<@http://localhost:4200/assets/test-helpers.js:29276:17 processModule@http://localhost:4200/assets/chunk.vendors-node_modules_pretender_dist_pretender_es_js-node_modules_qunit_qunit_qunit_js-node_mo-a05e2f.dac4c13058b8c0d88081.js:3856:622 module$1@http://localhost:4200/assets/chunk.vendors-node_modules_pretender_dist_pretender_es_js-node_modules_qunit_qunit_qunit_js-node_mo-a05e2f.dac4c13058b8c0d88081.js:3861:105 acceptance@http://localhost:4200/assets/test-helpers.js:29272:25 @http://localhost:4200/assets/plugins/test/discourse-custom-wizard_tests.js:408:32 Module.prototype.exports@http://localhost:4200/assets/vendor.js:11007:32 requireModule@http://localhost:4200/assets/vendor.js:10928:18 require@http://localhost:4200/assets/test-support.js:31593:16 loadModules/<@http://localhost:4200/assets/test-support.js:31936:17 loadModules@http://localhost:4200/assets/test-support.js:31935:27 @http://localhost:4200/assets/test-helpers.js:31034:12 @http://localhost:4200/assets/scripts/discourse-boot.js:20:12 @http://localhost:4200/assets/scripts/discourse-boot.js:21:3
```

**Pull request merged**
