### PR TITLE
Apply prettier 💄 

### PR DESCRIPTION
**Pull request by angusmcleod**

### CODE REVIEW

**Comment by angusmcleod** [comment]
@fzngagan Would you mind checking out the conflicts here? I had a look and I think they might be due to the updates you made since I raised this one. Just don't want to resolve them in the wrong way.

**Comment by fzngagan** [comment]
@angusmcleod 
The way here IMO is to resolve conflicts and run prettier on the file again. I'll take care of it in a few.

**Comment by fzngagan** [comment]
@angusmcleod 
I've resolved the conflicts and applied prettier on the resultant file. Now, you can see only formatting changes for the `similar-topics-validator.js.es6` file. :)
Also taking a look at the PR in detail now.

**Review by fzngagan — APPROVED** [review]
Looking fine. Happy to merge? @angusmcleod

**Pull request merged**
