### PR TITLE
DEV: Integrate subscription gem classes in rspec suite

### PR DESCRIPTION
**Pull request by angusmcleod**
I've tweaked the subscription client gem so we can just use the gem's models and tables in this plugin's rspec, which makes duplicating and stubbing them unnecessary. See further https://github.com/paviliondev/discourse_subscription_client

### CODE REVIEW

**Comment by merefield** [comment]
@angusmcleod the rspec changes look promising.  This wasn't the greatest thing I've written, the pages of warnings were a little rough edged.

Could you please elaborate slightly more on how this is intended to work - I see now that you are allowing the gems models and tables to be created during a test run - but how is fixture data getting in there?

**Review by merefield — COMMENTED** [review]
@angusmcleod the rspec changes look promising. The stubbing strategy wasn't the greatest thing I've written, the pages of warnings were a little rough edged.

Could you please elaborate slightly more on how this is intended to work - I see now that you are allowing the gems models and tables to be created during a test run so we don't need to stub them - but how is fixture data getting in there?

Also I presume you wouldn't take this approach if we didn't also own the gem?

**Comment by angusmcleod** [comment]
Sure thing

> Could you please elaborate slightly more on how this is intended to work - I see now that you are allowing the gems models and tables to be created during a test run so we don't need to stub them - but how is fixture data getting in there?

Subscriptions are already stubbed the [enable_subscription](https://github.com/paviliondev/discourse-custom-wizard/blob/main/spec/plugin_helper.rb#L11) method.

> Also I presume we wouldn't take this approach if we didn't also own the gem?

Why not?

**Comment by angusmcleod** [comment]
The tests, and the custom wizard code, doesn't call the subscription classes directly. They call the subscription methods in `CustomWizard::Subscription`. That's the single source of truth for subscriptions in the custom wizard plugin. That's why the Custom Wizard rspecs only need to stub the subscription methods in that class in [enable_subscription](https://github.com/paviliondev/discourse-custom-wizard/blob/main/spec/plugin_helper.rb#L11).

The reason we needed to create mocks of those classes was because ruby will throw an error when a class is referenced that doesn't exist, i.e. when `CustomWizard::Subscription` is loaded. As the classes were defined in a different plugin (i.e. discourse-subscription-client) we had to mock them for testing purposes, even though they weren't being used directly. Now that that plugin is a gem those classes do exist so there's no need to stub them. The stubs are just redefining pre-existing classes, which is why Custom Wizard specs are throwing a lot of warnings atm.

**Pull request merged**
