### PR TITLE
Add guest support

### PR DESCRIPTION
**Pull request by angusmcleod**

### CODE REVIEW

**Comment by merefield** [comment]
Looks good @angusmcleod, are we fully comfortable with the level of test coverage around Guest scenarios?

**Comment by angusmcleod** [comment]
@merefield I'll do another review of the test coverage on Monday and confirm then.

**Comment by angusmcleod** [comment]
@merefield This is ready for another review. Note that the guests feature is now an option in the "permitted" wizard attribute.

**Comment by angusmcleod** [comment]
@merefield Hold off on merging until we resolve this https://coop.pavilion.tech/t/make-wizards-available-to-non-users-anonymous-users/1333/39?u=angus

**Comment by angusmcleod** [comment]
@merefield Found an issue with guests and uploads.

**Comment by merefield** [comment]
image

No access to the guest wizard as a guest?

**Comment by angusmcleod** [comment]
@merefield Is guest access enabled?

**Comment by merefield** [comment]
DEPRECATION: Invoking the `<LinkTo>` component with positional arguments is deprecated.Please use the equivalent named arguments (`@route`, `@model`). ('discourse/plugins/discourse-custom-wizard/discourse/templates/admin-wizards-manager.hbs' @ L63:C12)  [deprecation id: ember-glimmer.link-to.positional-arguments] See https://deprecations.emberjs.com/v3.x#toc_ember-glimmer-link-to-positional-arguments for more details.

**Comment by merefield** [comment]
> @merefield Is guest access enabled?

test environment did not have correct branch installed + wrong sub level.

I've tested this locally and it's working now, thanks.

**Comment by angusmcleod** [comment]
@merefield 

> Are we fully comfortable with the level of test coverage around Guest scenarios?

Yes :)

> DEPRECATION: Invoking the <LinkTo> component with positional arguments is deprecated.Please use the equivalent named arguments (@route, @model). ('discourse/plugins/discourse-custom-wizard/discourse/templates/admin-wizards-manager.hbs' @ L63:C12) [deprecation id: ember-glimmer.link-to.positional-arguments] See https://deprecations.emberjs.com/v3.x#toc_ember-glimmer-link-to-positional-arguments for more details.

This code hasn't been changed by this PR. The fix should be in a seperate PR.

**Comment by merefield** [comment]
great stuff! 🎉

**Pull request merged**
