### PR TITLE
fix redirect after login

### PR DESCRIPTION
**Pull request by pacharanero**
javascript based cookie setting and redirect, removed ruby cookie handling

### CODE REVIEW

**Comment by angusmcleod** [comment]
@pacharanero hm this still isn't working for me. I've tried a few different tweaks and cookies are never saved.

**Comment by angusmcleod** [comment]
@pacharanero I wonder if this is browser dependent. I'm using firefox. Interestingly, the previous approach (i.e. setting the cookie in the rails controller) was also working for me on my local, then didn't work in your dev environment, or in production. Not sure what's going on here.

**Comment by pacharanero** [comment]
Possibly browser dependent. When I was researching why the cookie was not being set, I found some articles suggesting that Chrome doesn't store cookies when you are on a `localhost` URL (which I thought was a bit irregular as it would break a lot of stuff in development, so not sure if true)

I am on Brave browser, which is Chromium under the hood.

I am not sure how the previous approach _could_ have been working, because as far as I could see that bit of code was never being run in Rails after the modifications you made (changing the redirect to `/login' to happen in JS layer not Ruby). I figured that if the redirect to `/login` happens before Rails is even aware you are on the Custom Wizard page, then the Rails router and `CustomWizard::WizardController` would not be part of the request cycle. I did test that briefly and in a hacky way when I was working on it, with a `puts "This Code Is Being Run"` type of thing and the `before_action` was not seemingly being run.

For me, the cookie is being set fine in both local development on `localhost` and on a remote URL such as `test.thepavilion.io`, although I have to admit that in earlier work I did on it a few days before, the cookie was not set in javascript! So I'm prepared to believe this is brittle and might need improvement.

**Comment by angusmcleod** [comment]
@pacharanero If you can get this working consistently on development and production, happy for you to merge :+1:

**Comment by pacharanero** [comment]
Hmm, I reviewed this with a remote Discourse that I have SSH access to so I could get into the container and switch branches. It didn't work.

**Comment by angusmcleod** [comment]
@pacharanero I think I've cracked it. Our cookies were being set on the /w path, meaning they're not available at login.

Screen Shot 2019-10-17 at 11 19 10 AM

Adding a path to the redirect cookie seems to make this work consistently: https://github.com/paviliondev/discourse-custom-wizard/pull/17/commits/aab2662f9ca5ba6ce54651c24c7f518c52dcb2d4

Just tested in production on test.thepavilion.io and it's working :+1:

Merging and deploying to thepavilion.io

**Pull request merged**
